#Ligar a luz quando não há luz e quando um device tiver entrado na rede a menos de 5m
#Desligar todas as luzes e equipamentos após saída de casa

- alias: 'Turn presence light on'
  trigger:
    platform: numeric_state
    entity_id: sensor.illumination_34ce00fa67c5
    below: 50
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: time
      after: '22:00:00'
      before: '06:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce00fa67c5

- alias: 'Turn presence light off'
  trigger:
    platform: numeric_state
    entity_id: sensor.illumination_34ce00fa67c5
    above: 50
  condition:
    - condition: state
      entity_id: light.gateway_light_34ce00fa67c5
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_34ce00fa67c5

- alias: 'Fire Notification'
  trigger:
    platform: state
    entity_id: binary_sensor.smoke_sensor_158d0001d84137
    from: 'off'
    to: 'on'
  action:
    - service: script.activate_fire_alarm

- alias: 'Alert door open'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001ab3ef9
      from: 'off'
      to: 'on'
      for:
        seconds: 30
  action:
    - service: notify.family
      data:
        title: "Door opened"
        message: "You left entrance door opened"

- alias: 'Turn on fireplace'
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001d6be0a
      below: 10
    # - platform: state
    #   entity_id: media_player.samsung_tv_remote
    #   from: 'off'
    #   to: 'on'
  condition:
    # - condition: state
    #   entity_id: input_boolean.fireplace
    #   state: 'off'
    # - condition: numeric_state
    #   entity_id: sensor.temperature_158d0001d6be0a
    #   below: 10
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    # - condition: state
    #   entity_id: media_player.samsung_tv_remote
    #   state: 'on'
  action:
    - service: script.turn_on_fireplace

- alias: 'Turn off fireplace'
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001d6be0a
      above: 20
    - platform: state
      entity_id: media_player.samsung_tv_remote
      from: 'on'
      to: 'off'
  condition:
    # - condition: state
    #   entity_id: input_boolean.fireplace
    #   state: 'on'
  action:
    - service: script.turn_off_fireplace

- alias: 'Turn off outside lamp'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001ab3ef9
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: switch.wall_switch_right_158d0001a659d6
      from: 'off'
      to: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0001ab3ef9
      state: 'off'
    - condition: state
      entity_id: switch.wall_switch_right_158d0001a659d6
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0001a659d6

- alias: 'Toggle Felipe Tv'
  trigger:
    - platform: state
      entity_id: switch.wall_switch_left_158d0001a659ee
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.wall_switch_left_158d0001a659ee
      from: 'on'
      to: 'off'
  action:
    - service: script.toggle_felipe_tv
    - delay: '00:00:20'
    - service: script.change_felipe_tv_23


- alias: 'Store room light toggle'
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001b7b043
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001b7b043
      from: 'on'
      to: 'off'
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_right_158d0001715418



- alias: "New Device Connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: script.janet_speech_engine
      data:
        call_greeting: 1
        call_new_device: 1
      data_template:
        person: >-
          {{ trigger.event.data.name }}
