#binary_sensor.switch_158d0001a6751a
- alias: 'Toggle Lights from switch'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a6751a
      click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_right_158d000171558d

- alias: 'Turn TV off'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a6751a
      click_type: double
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.lg_webos_smart_tv

#binary_sensor.switch_158d0001b8f98c
- alias: 'Toggle toilet light'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b8f98c
      click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.wall_switch_right_158d000171543b

#binary_sensor.switch_158d0001b8f8e9
- alias: 'Turn off bedroom lights'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b8f8e9
      click_type: single
  condition:
    - condition: state
      entity_id: group.lights_bedroom
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d0001715478
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0001715478

- alias: 'Turn on bedroom light'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b8f8e9
      click_type: single
  condition:
    - condition: state
      entity_id: group.lights_bedroom
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d0001715478

- alias: 'Special time'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b8f8e9
      click_type: double
  condition:
    - condition: state
      entity_id: switch.wall_switch_right_158d0001715478
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d0001715478
    - service: switch.turn_on
      entity_id: switch.wall_switch_right_158d0001715478
    #Make LED red

- alias: 'Disable Special time'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b8f8e9
      click_type: double
  condition:
    - condition: state
      entity_id: switch.wall_switch_right_158d0001715478
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.wall_switch_right_158d0001715478
