- alias: 'Alarm triggered'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001ab3ef9
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: notify.family
      data:
        title: "Security"
        message: "Alarm triggered you are being robbed"
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34ce00fa67c5
        ringtone_id: 0
        ringtone_vol: 20
    - service: switch.turn_on
      entity_id: switch.wall_switch_right_158d0001715478
    - service: switch.turn_on
      entity_id: switch.wall_switch_left_158d0001660c72
    - service: light.turn_on
      data:
        entity_id: light.living_room_led
        effect: red_strobe
    - service: light.turn_on
      data:
        entity_id: light.bedroom_led
        effect: red_strobe
