- alias: 'Alarm triggered'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001ab3ef9
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: script.activate_house_alarm
