input_boolean:
  weather:
  weather_amsterdam:

weather:
  - platform: yweather
    woeid: 742676
  - platform: buienradar
    name: Amsterdam
    latitude: 52.379189 # !secret amsterdam_home_latitude
    longitude: 4.899431 # !secret amsterdam_home_longitude
    forecast: True

sensor:
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature
  - platform: buienradar
    monitored_conditions:
      - symbol
      - humidity
      - temperature
      - windspeed
      - pressure
